[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs_18"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-scripts --no-plugins",
  "composer dump-autoload --optimize --no-scripts"
]

[phases.build]
cmds = ["echo 'Build completed - skipping Laravel artisan commands'"]

[start]
cmd = "php artisan config:clear && php artisan cache:clear && php artisan serve --host=0.0.0.0 --port=$PORT"