[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = [
  "mkdir -p bootstrap/cache storage/logs storage/framework/cache storage/framework/sessions storage/framework/views",
  "chmod -R 777 storage bootstrap/cache",
  "COMPOSER_CACHE_DIR=/dev/null composer install --no-dev --optimize-autoloader --no-cache --no-scripts --no-plugins"
]

[phases.build]
cmds = [
  "touch .env",
  "echo 'APP_KEY=base64:$(openssl rand -base64 32)' >> .env",
  "echo 'APP_ENV=production' >> .env",
  "echo 'APP_DEBUG=false' >> .env",
  "php artisan config:clear || true",
  "php artisan cache:clear || true"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"