[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs_18"]

[phases.install]
cmds = [
  "mkdir -p /tmp/composer-cache",
  "composer install --no-dev --optimize-autoloader --no-cache",
  "composer dump-autoload --optimize"
]

[phases.build]
cmds = [
  "mkdir -p bootstrap/cache",
  "mkdir -p storage/logs",
  "mkdir -p storage/framework/cache",
  "mkdir -p storage/framework/sessions",
  "mkdir -p storage/framework/views",
  "chmod -R 775 storage bootstrap/cache",
  "php artisan key:generate --force"
]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT"