[build]
builder = "dockerfile"
dockerfilePath = "brain/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "quotingfast-brain"
source = "brain"

[services.variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:Ck7Rt1uiy5WGbrTFj1HBjymbBoA6zqih"
APP_NAME = "QuotingFast Brain"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"