[[services]]
name = "parcelvoy-platform"
source = "apps/platform"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
API_SECRET = "parcelvoy-secret-key-2025"
JWT_SECRET = "jwt-secret-key-2025"