services:
  - type: web
    name: brain-api
    env: docker
    dockerfilePath: ./brain/Dockerfile.render
    plan: free
    region: ohio
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d261qkfdiees738entk0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: parcelvoy_p64d
      - key: DB_USERNAME
        value: parcelvoy
      - key: DB_PASSWORD
        value: gGRLGwBBn90tEInwq9NeaG60uYhGXbE1
      - key: ALLSTATE_API_KEY
        value: quoting-fast
      - key: ALLSTATE_API_ENV
        value: testing
      - key: ALLSTATE_TEST_MODE
        value: true


