services:
  # Parcelvoy SMS/Email Platform - NEW
  - type: web
    name: parcelvoy-sms
    env: node
    region: oregon
    plan: starter
    rootDir: apps/platform
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm install --save-dev @types/koa && npm run build
    startCommand: npm start
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: parcelvoy-db
          property: connectionString
      - key: API_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Laravel Brain Lead Management - DOCKER SERVICE
  - type: web
    name: quotingfast-brain
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./brain/Dockerfile.render
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: PORT
        value: 80
      - key: DATABASE_URL
        fromDatabase:
          name: parcelvoy-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: errorlog
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    healthCheckPath: /

# Using existing parcelvoy-db database - no need to create a new one