services:
  # Parcelvoy SMS/Email Platform
  - type: web
    name: parcelvoy-platform
    env: node
    region: oregon
    plan: starter
    buildCommand: cd apps/platform && npm ci && npm run build
    startCommand: cd apps/platform && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: parcelvoy-db
          property: connectionString
      - key: API_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Laravel Brain Lead Management
  - type: web
    name: laravel-brain
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./brain/Dockerfile.render
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: parcelvoy-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: parcelvoy-db
    databaseName: parcelvoy_production
    user: parcelvoy_user
    region: oregon
    plan: starter