services:
  # Parcelvoy SMS/Email Platform - NEW
  - type: web
    name: parcelvoy-sms
    env: node
    region: oregon
    plan: starter
    buildCommand: cd apps/platform && npm ci && npm run build
    startCommand: cd apps/platform && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: quotingfast-db
          property: connectionString
      - key: API_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

  # Laravel Brain Lead Management - NEW PHP SERVICE
  - type: web
    name: quotingfast-brain
    env: php
    region: oregon
    plan: starter
    buildCommand: cd brain && composer install --no-dev --optimize-autoloader && php artisan key:generate --force && mkdir -p storage/framework/{cache,sessions,views} && mkdir -p storage/logs && mkdir -p bootstrap/cache
    startCommand: cd brain && php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: quotingfast-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: errorlog
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    healthCheckPath: /

databases:
  - name: quotingfast-db
    databaseName: quotingfast_production
    user: quotingfast_user
    region: oregon
    plan: starter