name: quotingfast-brain
services:
- name: web
  source_dir: brain
  github:
    repo: giltorres14/quotingfast-brain
    branch: main
  run_command: php artisan serve --host=0.0.0.0 --port=$PORT
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: APP_KEY
    type: SECRET
    value: base64:GENERATED_LARAVEL_KEY
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: ${db.PORT}
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync

databases:
- name: db
  engine: PG
  version: "13"
  size: basic

jobs:
- name: migrate
  source_dir: brain
  github:
    repo: giltorres14/quotingfast-brain
    branch: main
  run_command: php artisan migrate --force
  environment_slug: php